# Generated by Django 4.2.3 on 2023-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'High'), ('B', 'Medium'), ('C', 'Low')], default='High', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In progress', 'In Progress'), ('Awaiting', 'Awaiting'), ('Completed', 'Completed')], default='In_progress', max_length=20),
        ),
    ]
